### ISSUE TITLE
Vote on Natural Language Localisation Implementation 

### ISSUE THREAD

**Issue by Salkimmich** [ossf/education#38]
We've agreed to move Section 1.5 Language Localisation to Section 2.5 - but we should have a vote on how to implement it. 

From my read, Section 1.5 was written with the intent to provide a dedicated language localiser for the top natural languages. I'd recommend we use an open source glossary ie: https://github.com/cncf/glossary/blob/main/LOCALIZATION.md

For this issue, can we decide on an optimal path forward between:
1. Hire localisation expert for each top natural language - might not be efficient but will have full coverage 
2. Implement OS Glossary for cybersecurity terminology - will not have full coverage
3. Implement both localisers and an OS glossary - the best of both worlds approach? 

Stream 1 Section 1.5
https://github.com/ossf/education/blob/4c94958e898f8f99bf5cde47d1ac927c08585272/plan/1.0%20Collect%20and%20Curate%20Content.md#

Stream 2 Section 2.4
https://github.com/ossf/education/blob/4c94958e898f8f99bf5cde47d1ac927c08585272/plan/2.0%20Expand%20Training.md

**Comment by thiswayman** [comment]
**Voting 2** as it seems to be a better iterative first step to reach 3.

**Comment by TheFoxAtWork** [comment]
3️⃣  - we can start with 2 and go from there, but three seems like the right end goal

**Comment by blabla1337** [comment]
Voting 2 - and revise in year 2

**Comment by ran-dall** [comment]
Voting 2 as well

**Comment by judyobrienie** [comment]
2 looks like the more viable option to get started and once gaps/needs are identified can move to 3

**Comment by danjconn** [comment]
Voting 2

**Comment by Salkimmich** [comment]
Aim 2 it is: building an OS glossary, with an aim to bring on localizing translators in a Y2
