### ISSUE TITLE
VOTE - Adopt or Adjust SIG Charter

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/education#58]
Team - please review our SIG Charter(1) and vote here to express your opinion to adopt it, or provide feedback you desire to see changed prior to adoption.  Thanks.

(1) - https://github.com/ossf/education/blob/main/CHARTER.md

**Comment by ran-dall** [comment]
+1 :white_check_mark: Approve

**Comment by Salkimmich** [comment]
+1 ✅ Approve

**Comment by caabernathy** [comment]
+1 ✅ Approve
