### ISSUE TITLE
Plan review and comments

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/education#64]
SIG & friends – The EDU.SIG SIG has been working since summer to revise the initial OpenSSF’s Mobilization Plan(1) Stream 1. We are pleased to announce that our work is nearly complete and we are seeking feedback on the newly revised plan(2) from the SIG & friends prior to officially sharing it with the TAC and GB the first full week of December.

Please read the plan (Summary and three sections [the final section where all of the “Costs” are pulled together is actively being updated and is not ready at this time, but will be for the final proposal]) and provide us feedback in this issue.

(1) - https://openssf.org/oss-security-mobilization-plan/
(2) - https://github.com/ossf/education/tree/main/plan

**Comment by SecurityCRob** [comment]
SIG & WG - please provide feedback by 23Dec2022

**Comment by jchestershopify** [comment]
I'm only up to a skim so far but: outstanding work.

**Comment by caabernathy** [comment]
From Education SIG DEI subcommittee, proposed list of work items to consider and add to the overall plan:
1. Mentorship
1. Skills Develpment
    * Technical
        * Ex: Using Git
    * Professional
        * Project Management
        * Collaboration
        * Presentation
        * Writing
1. Industry Experience
    * Internships
    * Fellowships
1. Career Preparation
    * Interview prep
    * Resume writing
    * Coding practice
    * Digital portfolio

Ideas include:
1. Leveraging existing [LF initiatives](https://www.linuxfoundation.org/about/diversity-inclusivity)
1. Working with HBCUs, HSIs to identify experience and outcome gaps from their current industry partnerships.
1. Partnering with organizations that focus on providing mentorship (and career preparation services) to underserved communities, ex: Women in Cybersecurity.
1. Working with a new Alpha-Omega DEI initiative to bring mentorship opportunities and build interview skills.
1. Exploring partnership opportunities with critical open source projects to help folks build a digital portfolio of work in the security space.
1. Challginging premier OpenSSF members to sponsor (hire/intern) a certain number of people from underserved communities who go through our programs.

Other bubbling ideas that we did not have time to discuss on the 20221215 meeting:
1. Reviewing existing education resources for accessibility gaps and suitability for neurodiverse learners as well as those from various backgrounds.
1. Partnering with neurodiversity organizations to drive better hiring outcomes for those who go through security training.

**Comment by SecurityCRob** [comment]
> From Education SIG DEI subcommittee, proposed list of work items to consider and add to the overall plan:
> 
>     1. Mentorship
> 
>     2. Skills Develpment
>        
>        * Technical
>          
>          * Ex: Using Git
>        * Professional
>          
>          * Project Management
>          * Collaboration
>          * Presentation
>          * Writing
> 
>     3. Industry Experience
>        
>        * Internships
>        * Fellowships
> 
>     4. Career Preparation
>        
>        * Interview prep
>        * Resume writing
>        * Coding practice
>        * Digital portfolio
> 
> 
> Ideas include:
> 
>     1. Leveraging existing [LF initiatives](https://www.linuxfoundation.org/about/diversity-inclusivity)
> 
>     2. Working with HBCUs, HSIs to identify experience and outcome gaps from their current industry partnerships.
> 
>     3. Partnering with organizations that focus on providing mentorship (and career preparation services) to underserved communities, ex: Women in Cybersecurity.
> 
>     4. Working with a new Alpha-Omega DEI initiative to bring mentorship opportunities and build interview skills.
> 
>     5. Exploring partnership opportunities with critical open source projects to help folks build a digital portfolio of work in the security space.
> 
>     6. Challginging premier OpenSSF members to sponsor (hire/intern) a certain number of people from underserved communities who go through our programs.
> 
> 
> Other bubbling ideas that we did not have time to discuss on the 20221215 meeting:
> 
>     1. Reviewing existing education resources for accessibility gaps and suitability for neurodiverse learners as well as those from various backgrounds.
> 
>     2. Partnering with neurodiversity organizations to drive better hiring outcomes for those who go through security training.

How can we get this integrated into the plan prior to us sharing with the TAC in 3 weeks?

**Comment by SecurityCRob** [comment]
The plan first draft was complete and shared with the TAC,GC, and gb
